// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzJLQNfsRnBBpgGPBQpmETeUZuLsEn5JA',
    appId: '1:503248905696:web:2d4a7f620cc6f038d8b785',
    messagingSenderId: '503248905696',
    projectId: 'winstar-8fbeb',
    authDomain: 'winstar-8fbeb.firebaseapp.com',
    storageBucket: 'winstar-8fbeb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoSOQqC9dzBB5oU8iZRSChI33bhavOZKA',
    appId: '1:503248905696:android:068cc2d2b5edd0f5d8b785',
    messagingSenderId: '503248905696',
    projectId: 'winstar-8fbeb',
    storageBucket: 'winstar-8fbeb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSrwLzoY6fzlLbQy4Fx3rFR3UDI9JOVnk',
    appId: '1:503248905696:ios:6a4b4645cb954458d8b785',
    messagingSenderId: '503248905696',
    projectId: 'winstar-8fbeb',
    storageBucket: 'winstar-8fbeb.firebasestorage.app',
    iosBundleId: 'com.nijatech.winstar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSrwLzoY6fzlLbQy4Fx3rFR3UDI9JOVnk',
    appId: '1:503248905696:ios:6a4b4645cb954458d8b785',
    messagingSenderId: '503248905696',
    projectId: 'winstar-8fbeb',
    storageBucket: 'winstar-8fbeb.firebasestorage.app',
    iosBundleId: 'com.nijatech.winstar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzJLQNfsRnBBpgGPBQpmETeUZuLsEn5JA',
    appId: '1:503248905696:web:dae039325ac35adad8b785',
    messagingSenderId: '503248905696',
    projectId: 'winstar-8fbeb',
    authDomain: 'winstar-8fbeb.firebaseapp.com',
    storageBucket: 'winstar-8fbeb.firebasestorage.app',
  );
}
