// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQCmYSOrcG6545dFwi-RAcfh2Z0GjPjxE',
    appId: '1:404611494996:web:bdf21a552c8a8a85c569c1',
    messagingSenderId: '404611494996',
    projectId: 'winstar-9aee2',
    authDomain: 'winstar-9aee2.firebaseapp.com',
    storageBucket: 'winstar-9aee2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd7PMjBftCr3zhTM70vc-Z89eYxxgmjTo',
    appId: '1:404611494996:android:1ee7b87348f02cc3c569c1',
    messagingSenderId: '404611494996',
    projectId: 'winstar-9aee2',
    storageBucket: 'winstar-9aee2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWveKw6Gx_m6WiLdk0Pbdxrucm7cW_iQU',
    appId: '1:404611494996:ios:ec00502bec0f19d0c569c1',
    messagingSenderId: '404611494996',
    projectId: 'winstar-9aee2',
    storageBucket: 'winstar-9aee2.firebasestorage.app',
    iosBundleId: 'com.nijatech.winstar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWveKw6Gx_m6WiLdk0Pbdxrucm7cW_iQU',
    appId: '1:404611494996:ios:ec00502bec0f19d0c569c1',
    messagingSenderId: '404611494996',
    projectId: 'winstar-9aee2',
    storageBucket: 'winstar-9aee2.firebasestorage.app',
    iosBundleId: 'com.nijatech.winstar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQCmYSOrcG6545dFwi-RAcfh2Z0GjPjxE',
    appId: '1:404611494996:web:9e4a5ea92ab1b686c569c1',
    messagingSenderId: '404611494996',
    projectId: 'winstar-9aee2',
    authDomain: 'winstar-9aee2.firebaseapp.com',
    storageBucket: 'winstar-9aee2.firebasestorage.app',
  );
}
